# Generated by Django 2.0.4 on 2018-04-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='updated_by',
            new_name='last_updated_by',
        ),
    ]
