# Generated by Django 2.0.4 on 2018-04-21 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20180421_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updated_by',
            new_name='last_updated_by',
        ),
    ]
