# Generated by Django 2.0.4 on 2018-05-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20180421_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='disliked',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
